python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTCS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTCY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTOG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTTR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BTTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWACU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWACW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWAY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWBBP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWCAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWEN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWFG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWMN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWMX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWNB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWSN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BWXT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BXC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BXMT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BXMX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BXP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BXRX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BXSL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYFC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYND.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYNO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYNOU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYRN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYSI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BYTS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BZFD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BZFDW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BZH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/BZUN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/C.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAAP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAAS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CABA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CABO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CACC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CACI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CADE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CADL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAJ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAKE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CALA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CALB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CALM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CALT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CALX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAMP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAMT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CANF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CANG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CANO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAPD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAPL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAPR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CARA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CARE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CARG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CARR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CARS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CARV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CASA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CASH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CASI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CASS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CASY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CAT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CATC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CATO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CATY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBAN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBAT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBAY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBFV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBIO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBNK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBOE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBOE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBRE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBRG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBRGW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBRL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBSH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CBZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCAI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCAP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCBG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCCC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCCS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCEL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCEP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCJ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCLP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCMP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCNC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCNE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCNEP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCOI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCRD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCRN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCSI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCTS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCVI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCXI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CCZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDAK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDAQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDAQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDAQW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDAY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDEV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDLX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDMO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDNA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDNS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDRE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDRO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDROW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDXC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDXS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDZI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CDZIP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEAD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEADW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CECE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEIX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CELC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CELH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CELU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CELUW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CELZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEMI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CENN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CENQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CENQU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CENQW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CENT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CENTA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CENX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEPU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEQP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CERE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CERN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CERS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CERT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CET.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CETX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CETXP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CEVA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFBK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFFEU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFFEW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFFI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFFN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFFSU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFFSW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFIV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFIVW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFLT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFMS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFRX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFSB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFVI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFVIU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CFVIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGABL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGBD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGEM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGEN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGNT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGNX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGRN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CGTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHAA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHCI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHCT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHDN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHEAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHEF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHEK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHEKZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHGG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHKEL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHKEW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHKEZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHKP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHMG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHMI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHNG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHNGU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHNR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHPT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHRA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHRB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHRS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHRW,.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHSCL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHSCM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHSCN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHSCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHSCP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHTR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHUY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHWA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHWAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHWY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CHY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIDM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIEN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIFR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIFRW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIGI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CII.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIIG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIIGU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CINC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CINF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CING.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CINGW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CINT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CION.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CISO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CITE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CITEU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIVB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIVI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIXX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CIZN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CJJD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CKPT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CKX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLAA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLAQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLAQR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLAQW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLBK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLBR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLBS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLBT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLBTW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLDT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLDX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLEU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLFD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLGN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLIM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLINR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLINU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLINW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLIR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLLS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLMT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLNE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLNN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLNNW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLOE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLOER.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLOV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLPR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLPS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLPT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLRB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLRCU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLRM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLRMU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLRMW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLRO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLSD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLSK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLSN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLST.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLVR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLVRW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLVS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLVT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLWT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CLXT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMAX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMAXW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMBM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMCA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMCAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMCL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMCM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMCSA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMCT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMCTP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CME.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMLS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMMB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMPI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMPO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMPOW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMPR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMPS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMPX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMRA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMRAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMRE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMRX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMSA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMSC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMSD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMTG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMTL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CMU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNCE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CND.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNDA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNDB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNDT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNET.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNEY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNFR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNGL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNGLU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNGLW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNHI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNMD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNNB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNNE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNOB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNOBP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNSL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNSP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNTA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNTB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNTG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNTQW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNTY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNVY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNXC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CNXN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COCP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CODI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COFS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COGT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COHN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COHR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COHU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COIN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COKE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COLB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COLD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COLI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COLIU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COLIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COLL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COLM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COMM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COMP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COMS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COMSP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COMSW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CONN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CONX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COOL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COOLU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COOLW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COOP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CORR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CORS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CORT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CORZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COSM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CORZW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COST.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COTY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COUP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COUR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COVA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COVAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CONXU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CONXW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COOK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COVAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COWN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/COWNL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPAAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPAQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPAQU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPAQW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPAR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPARU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPARW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPHC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPHI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPIX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPLP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPNG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPOP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPRI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPRT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPRX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPSH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPSI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPSS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPTAG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPTAL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPTK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPTN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPTNW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre2/CPUH.py
